app:
  adminPassword: changeme
  auth: true
  slackSigningSecret: See README for instructions
  newSignupWebhook: See README for instructions
  ingress:
    enabled: true
codeGen:
  image: sslhep/servicex_code_gen_func_adl_xaod
didFinder:
  pullPolicy: Always
gridAccount: bgalewsk
minio:
  ingress:
    enabled: true
    hosts:
    - "xaod-minio.uc.ssl-hep.org"
  persistence:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: true
postgres:
  enabled: true
postgresql:
  persistence:
    enabled: true
    storageClass: rook-ceph-block
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
preflight:
  pullPolicy: Always
rabbitmq:
  metrics:
    enabled: true
    plugins: rabbitmq_prometheus
    podAnnotations:
      prometheus.io/port: '9419'
      prometheus.io/scrape: "true"
    prometheusRule:
      additionalLabels: {}
      enabled: false
      namespace: ""
      rules: []
    serviceMonitor:
      additionalLabels: {}
      enabled: true
      honorLabels: false
      interval: 30s
    persistence:
      enabled: true
      storageClass: rook-ceph-block
transformer:
  autoscalerEnabled: false
  pullPolicy: Always
